name: yuonsoft
description: yuonsoft homepage

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  file_picker: ^4.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
